### ISSUE TITLE
Error when updated dropbox

### ISSUE THREAD

**Issue by titpetric** [janeczku/docker-dropbox#14]
When the container starts it downloads a newer dropbox and tries to run it:

~~~
Checking for latest Dropbox version...
Latest   : 18.4.32
Installed: 18.4.32
Dropbox is up-to-date
Starting dropboxd (18.4.32)...
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "__main__.py", line 3, in <module>
ImportError: No module named os
~~~

**Comment by titpetric** [comment]
I can confirm that it's working with 16.x version, which I have running on another long-running instance. Of course, it will only work until I restart the container and it upgrades to 18.x :(

**Comment by titpetric** [comment]
os.pyc is packaged in library.zip of the dropbox build, the fault is caused interally by a non-functioning zipimport, it seems - https://docs.python.org/2/library/zipimport.html ; the issue is that the dropbox binary as well as library.zip contain a folder with the name "dropbox" so I can't just unpack it as the filesystem isn't able to hold a folder and a file with the same name. Any other ideas?

**Comment by titpetric** [comment]
It seems it was resolved in upstream in recent versions. I can't replicate the bug anymore.
