### ISSUE TITLE
libatomic missing, required by 85.4.155

### ISSUE THREAD

**Issue by adamkdean** [janeczku/docker-dropbox#38]
```
Latest   : 85.4.155
Installed: 85.4.155
```

```
Traceback (most recent call last):
  File "dropbox/client/main.pyc", line 7919, in main
  File "dropbox/client/main.pyc", line 7843, in main_startup
  File "dropbox/client/main.pyc", line 942, in __init__
  File "dropbox/sync_engine_boundary/factory.pyc", line 147, in make_default_file_system
  File "dropbox/sync_engine_boundary/factory.pyc", line 99, in __init__
  File "dropbox/sync_engine_boundary/factory.pyc", line 118, in _initialize_classes
  File "dropbox/sync_engine/nucleus/classic_client/sync_engine.pyc", line 276, in <module>
  File "dropbox/sync_engine/nucleus/classic_client/thin_adapter/in_proc.pyc", line 98, in <module>
  File "dropbox/sync_engine/nucleus/classic_client/wrapped_thin_client.pyc", line 26, in <module>
  File "dropbox/sync_engine/nucleus/thin_client/client.pyc", line 28, in <module>
  File "dropbox/foundation/metrics/amp/remote_sink.pyc", line 10, in <module>
ImportError: libatomic.so.1: cannot open shared object file: No such file or directory
!! dropbox: fatal python exception:
['Traceback (most recent call last):\n', '  File "dropbox/client/main.pyc", line 7919, in main\n', '  File "dropbox/client/main.pyc", line 7843, in main_startup\n', '  File "dropbox/client/main.pyc", line 942, in __init__\n', '  File "dropbox/sync_engine_boundary/factory.pyc", line 147, in make_default_file_system\n', '  File "dropbox/sync_engine_boundary/factory.pyc", line 99, in __init__\n', '  File "dropbox/sync_engine_boundary/factory.pyc", line 118, in _initialize_classes\n', '  File "dropbox/sync_engine/nucleus/classic_client/sync_engine.pyc", line 276, in <module>\n', '  File "dropbox/sync_engine/nucleus/classic_client/thin_adapter/in_proc.pyc", line 98, in <module>\n', '  File "dropbox/sync_engine/nucleus/classic_client/wrapped_thin_client.pyc", line 26, in <module>\n', '  File "dropbox/sync_engine/nucleus/thin_client/client.pyc", line 28, in <module>\n', '  File "dropbox/foundation/metrics/amp/remote_sink.pyc", line 10, in <module>\n', 'ImportError: libatomic.so.1: cannot open shared object file: No such file or directory\n'] (error 3)
```

**Comment by tomp61** [comment]
I'm getting this error, too.  Prior to that (a few days ago) I also noticed that the client stopped syncing files that were added to the Dropbox folder after the client had started running.  I was wondering if that might not be an issue with new dependencies in the system libraries the client is using to monitor filesystem changes...

**Comment by adamkdean** [comment]
I fixed this in a fork https://github.com/adamkdean/docker-dropbox (adamkdean/dropbox on Hub) and also incorporated https://github.com/janeczku/docker-dropbox/pull/32 too.

Looks like this repo is no longer maintained so I might pick this up next week.

@tomp61 I had an issue where files created on the machine weren't synchronised out, so setup an hourly cron to restart the container. Hacky, but did the trick. Will look into it next week.
