### ISSUE TITLE
dropbox won't start due to missing libglapi.so.0

### ISSUE THREAD

**Issue by dolhop** [janeczku/docker-dropbox#46]
```
# sudo docker run --rm --name=dropbox janeczku/dropbox
Unable to find image 'janeczku/dropbox:latest' locally
latest: Pulling from janeczku/dropbox
6a5a5368e0c2: Pull complete 
eb0746ae806a: Pull complete 
0d5af593ff41: Pull complete 
f684e23016fe: Pull complete 
ad25e946dda5: Pull complete 
1420ad85d40d: Pull complete 
Digest: sha256:8931b2b86d64148fe60c1d9fa4d169ac1bfe47eb3c88daa032520243bc93a170
Status: Downloaded newer image for janeczku/dropbox:latest
DBOX_UID variable not specified, defaulting to dropbox user id (1000)
DBOX_GID variable not specified, defaulting to dropbox user group id (1000)
Checking for latest Dropbox version...
Latest   : 94.4.384
Installed: 11.4.21
Downloading Dropbox v94.4.384...
######################################################################## 100.0%
Installing new version...
Dropbox updated to v94.4.384
Starting dropboxd (94.4.384)...
dropbox: locating interpreter
!! dropbox: failed to create log file (Permission denied)!
dropbox: initializing
dropbox: initializing python 3.7.5
dropbox: setting program path '/opt/dropbox/dropbox-lnx.x86_64-94.4.384/dropbox'
dropbox: setting python path '/opt/dropbox/dropbox-lnx.x86_64-94.4.384:/opt/dropbox/dropbox-lnx.x86_64-94.4.384/python-packages.zip'
dropbox: python initialized
dropbox: running dropbox
dropbox: setting args
dropbox: applying overrides
dropbox: running main script
dropbox: load fq extension '/opt/dropbox/dropbox-lnx.x86_64-94.4.384/cryptography.hazmat.bindings._constant_time.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/opt/dropbox/dropbox-lnx.x86_64-94.4.384/cryptography.hazmat.bindings._openssl.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/opt/dropbox/dropbox-lnx.x86_64-94.4.384/cryptography.hazmat.bindings._padding.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/opt/dropbox/dropbox-lnx.x86_64-94.4.384/psutil._psutil_linux.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/opt/dropbox/dropbox-lnx.x86_64-94.4.384/psutil._psutil_posix.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/opt/dropbox/dropbox-lnx.x86_64-94.4.384/apex._apex.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/opt/dropbox/dropbox-lnx.x86_64-94.4.384/tornado.speedups.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/opt/dropbox/dropbox-lnx.x86_64-94.4.384/PyQt5.QtWidgets.cpython-37m-x86_64-linux-gnu.so'
Traceback (most recent call last):
  File "dropbox/client/main.pyc", line 262, in <module>
  File "dropbox/foundation/navigation_service/factory.pyc", line 19, in <module>
  File "dropbox/foundation/navigation_service/navigation_service_impl.pyc", line 57, in <module>
  File "dropbox/foundation/html_views/electron/manager_factory.pyc", line 13, in <module>
  File "dropbox/foundation/html_views/local/common/manager.pyc", line 33, in <module>
  File "dropbox/client/features/model_registry.pyc", line 13, in <module>
  File "dropbox/client/features/generated_models.pyc", line 279, in <module>
  File "dropbox/client/features/previews/view_anchor.pyc", line 104, in <module>
  File "<_bootstrap_overrides>", line 153, in load_module
ImportError: libglapi.so.0: cannot open shared object file: No such file or directory
!! dropbox: fatal python exception:
['Traceback (most recent call last):\n', '  File "dropbox/client/main.pyc", line 262, in <module>\n', '  File "dropbox/foundation/navigation_service/factory.pyc", line 19, in <module>\n', '  File "dropbox/foundation/navigation_service/navigation_service_impl.pyc", line 57, in <module>\n', '  File "dropbox/foundation/html_views/electron/manager_factory.pyc", line 13, in <module>\n', '  File "dropbox/foundation/html_views/local/common/manager.pyc", line 33, in <module>\n', '  File "dropbox/client/features/model_registry.pyc", line 13, in <module>\n', '  File "dropbox/client/features/generated_models.pyc", line 279, in <module>\n', '  File "dropbox/client/features/previews/view_anchor.pyc", line 104, in <module>\n', '  File "<_bootstrap_overrides>", line 153, in load_module\n', 'ImportError: libglapi.so.0: cannot open shared object file: No such file or directory\n'] (error 3)
```

**Comment by ecnepsnai** [comment]
Judging by the number of open issues and lack of commit activity I worry this project might be abandoned. Regardless I submitted a PR that resolves the issue.

**Comment by nwalet** [comment]
Good to see--you may want to post on  adamkdean / docker-dropbox, where there is an updated and reasonably maintained fork.

**Comment by otherguy** [comment]
@ecnepsnai I have a maintained fork at [otherguy/docker-dropbox](https://github.com/otherguy/docker-dropbox).
